name: Feature request
description: Request new feafure
title: "[Feature]: "
labels: ["feature"]
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: request
    attributes:
      label: Type of request?
      description: Select type of your request
      options:
        - New Feature
      default: 0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What is the OS which you want to suggest?
      options:
        - Microsoft Windows
        - Linux
        - Ubuntu
        - macOS
        - iOS
        - Android
      default: 0
    validations:
      required: true
  - type: textarea
    id: what-suggest
    attributes:
      label: What are the details of your suggestion
      description: Explain what you want
      placeholder: Feature details!
      value: "Feature details!"
    validations:
      required: true
